In [1]:
import numpy as np

In [2]:
array = np.array([[0,1,2],[3,4,5],[6,7,8]])
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# Dimensiones para un array
array.ndim

2

In [4]:
# Número de filas y columnas para un array
array.shape 

(3, 3)

In [5]:
# Tipo para un array
array.dtype.name

'int32'

In [6]:
a.shape = (9,1)
a

NameError: name 'a' is not defined

In [7]:
# Suma o resta entre array
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])
a-b

array([-1, -1, -1, -1])

In [8]:
a+b

array([ 3,  7, 11, 15])

In [9]:
# Potencia para un array
b**2

array([ 4, 16, 36, 64], dtype=int32)

In [10]:
np.square(b)

array([ 4, 16, 36, 64], dtype=int32)

In [11]:
# Operaciones trigonometricas para un array
np.sin(a)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ])

In [12]:
# Operaciones condiciones para un array
a>1

array([False,  True,  True,  True])

In [13]:
# Multiplicación de matrices
m1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
m2 = np.array([[8,7,6],[5,4,3],[2,1,0]])
m1*m2

array([[ 0,  7, 12],
       [15, 16, 15],
       [12,  7,  0]])

In [14]:
# Producto punto entre matrices
np.dot(m1,m2)

array([[ 9,  6,  3],
       [54, 42, 30],
       [99, 78, 57]])

In [15]:
# Incluir valores nulos en array
array = np.array([1.2, 3.1, np.nan, 4.2])
array

array([1.2, 3.1, nan, 4.2])

In [16]:
# Remplazo de valores nulos en el array
array[np.isnan(array)] = 5.5
array

array([1.2, 3.1, 5.5, 4.2])

In [17]:
# Convertir lista en un array
list = [1.2, 3.1, 5.5, 4.2]
array = np.array(list)
array

array([1.2, 3.1, 5.5, 4.2])

In [18]:
# Medidas estadisticas
print("Mediana =", array.mean())
print("Media =", np.median(array))
print("Rango (Max-Min =", np.ptp(array))
print("Desviación estandar =", array.std())
print("80th percentil =", np.percentile(array, 80))
print("0.3 quartil =", np.quantile(array, 0.3))

Mediana = 3.5
Media = 3.6500000000000004
Rango (Max-Min = 4.3
Desviación estandar = 1.5763882770434445
80th percentil = 4.720000000000001
0.3 quartil = 2.9099999999999997


In [19]:
# Indices de datos en un matriz
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a[1,1]

4

In [20]:
a[1,:]

array([3, 4, 5])

In [21]:
a[:,0]

array([0, 3, 6])

In [22]:
a[:,-1] # ultima columna

array([2, 5, 8])

In [23]:
# Convertir una matriz en array
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a.shape = (9,1)
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])