In [1]:
import numpy as np

In [2]:
array = np.array([[0,1,2],[3,4,5],[6,7,8]])
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
# Dimensiones para un array
array.ndim

2

In [4]:
# Número de filas y columnas para un array
array.shape 

(3, 3)

In [5]:
# Tipo para un array
array.dtype.name

'int32'

In [6]:
# Suma o resta entre array
a = np.array([1,3,5,7])
b = np.array([2,4,6,8])
a-b

array([-1, -1, -1, -1])

In [7]:
a+b

array([ 3,  7, 11, 15])

In [8]:
# Potencia para un array
b**2

array([ 4, 16, 36, 64], dtype=int32)

In [9]:
np.square(b)

array([ 4, 16, 36, 64], dtype=int32)

In [10]:
# Operaciones trigonometricas para un array
np.sin(a)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ])

In [11]:
# Operaciones condiciones para un array
a>1

array([False,  True,  True,  True])

In [12]:
# Multiplicación de matrices
m1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
m2 = np.array([[8,7,6],[5,4,3],[2,1,0]])
m1*m2

array([[ 0,  7, 12],
       [15, 16, 15],
       [12,  7,  0]])

In [13]:
# Producto punto entre matrices
np.dot(m1,m2)

array([[ 9,  6,  3],
       [54, 42, 30],
       [99, 78, 57]])

In [14]:
# Incluir valores nulos en array
array = np.array([1.2, 3.1, np.nan, 4.2])
array

array([1.2, 3.1, nan, 4.2])

In [15]:
# Remplazo de valores nulos en el array
array[np.isnan(array)] = 5.5
array

array([1.2, 3.1, 5.5, 4.2])

In [16]:
# Convertir lista en un array
list = [1.2, 3.1, 5.5, 4.2]
array = np.array(list)
array

array([1.2, 3.1, 5.5, 4.2])

In [17]:
# Medidas estadisticas
print("Mediana =", array.mean())
print("Media =", np.median(array))
print("Rango (Max-Min =", np.ptp(array))
print("Desviación estandar =", array.std())
print("80th percentil =", np.percentile(array, 80))
print("0.3 quartil =", np.quantile(array, 0.3))

Mediana = 3.5
Media = 3.6500000000000004
Rango (Max-Min = 4.3
Desviación estandar = 1.5763882770434445
80th percentil = 4.720000000000001
0.3 quartil = 2.9099999999999997


In [18]:
# Indices de datos en un matriz
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a[1,1]

4

In [19]:
a[1,:]

array([3, 4, 5])

In [20]:
a[:,0]

array([0, 3, 6])

In [21]:
a[:,-1] # ultima columna

array([2, 5, 8])

In [22]:
# Convertir una matriz en array
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a.shape = (9,1)
a

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [24]:
a.transpose()


array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [25]:
c = np.linspace(0,1,20)
c

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [26]:
x1 = np.array([1,2,3,4,5,6,7,8,9])
x1.shape

(9,)

In [27]:
x2 = x1[:, np.newaxis]
x2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [28]:
x2.shape

(9, 1)

In [29]:
x3 = np.array([10,11,12])
x4 = x2 + x3
x4

array([[11, 12, 13],
       [12, 13, 14],
       [13, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19],
       [18, 19, 20],
       [19, 20, 21]])

In [30]:
x5 = x4[:,np.newaxis,1]
x5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [31]:
x5 = x4[:,1]
x5

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
array = np.array([[[1,1,1],[2,2,2],[3,3,3,]]])
print(array)

[[[1 1 1]
  [2 2 2]
  [3 3 3]]]


In [33]:
array = np.squeeze(array)
print(array)

[[1 1 1]
 [2 2 2]
 [3 3 3]]
